# Generated by start-provisioner.sh — do not edit by hand
# Placeholders: __STAND_IP__ __TFTP_ROOT__ __IFACE_LINE__ __DHCP_LINES__ __PID_DIR__ __LOG_DIR__

port=0
bind-dynamic
__IFACE_LINE__
listen-address=__STAND_IP__
except-interface=lo

enable-tftp
tftp-root=__TFTP_ROOT__
tftp-no-fail

# DHCP (may be empty if ENABLE_DHCP=0)
__DHCP_LINES__

dhcp-leasefile=__PID_DIR__/dnsmasq.leases
pid-file=__PID_DIR__/dnsmasq.pid
log-facility=__LOG_DIR__/dnsmasq.log
log-dhcp

# Prefer our TFTP next-server for PXE/U-Boot clients we lease
dhcp-option=66,__STAND_IP__
