#!/bin/sh
if [ "$interface" = "end1" ] && [ -n "$new_routers" ]; then
    case "$reason" in
        BOUND|RENEW|REBIND|REBOOT)
            ip route replace default via $new_routers dev end1 metric 100 2>/dev/null || true
            ;;
    esac
fi
