#!/bin/sh
# Soft PHY renegotiate for configured eth0/eth1 after networking first bring-up.
# Complements net-watchdog / fix-eth; avoids "no ping until cable re-plug" on
# cold boot (IP101 / EMAC autoneg stall). Soft only — no MDIO unbind loops.
log() { logger -t sa02m-eth-coldboot -- "$*"; }

# Resolver belt. An ifup that died on the gateway step never ran its if-up.d
# hooks, so /etc/resolv.conf can be empty while carrier and IP look fine — the
# `carrier already up, skip` branch below is exactly the boot where nothing
# else in the recovery ladder runs afterwards. Guarded on -x so a partial
# deploy degrades to today. Contract: docs/contracts/boot-network-dns.md
DNS_ENSURE_BIN=/usr/local/sbin/sa02m-dns-ensure.sh
dns_ensure() {
    [ -x "$DNS_ENSURE_BIN" ] || return 0
    "$DNS_ENSURE_BIN" "$1" >/dev/null 2>&1 || true
}

# ── BOOTSTRAP SHIM — delete when the condition below is met ────────────────
# WHY: sa02m-dns-ensure.service IS delivered by web update (the OTA allowlist
# takes /etc/systemd/system/sa02m-*), but the updater only runs `systemctl
# enable` on units listed in the manifest's services.enable — and on the ONLINE
# path that manifest is generated by the runner ALREADY INSTALLED on the device,
# before anything is deployed (sa02m-update-runner.sh: prepare_github_overlay,
# then self_reexec_before_deploy re-execs that same old binary). So a board
# updating from a pre-1.0.6.6 runner receives the unit DISABLED, and the new
# enable list only takes effect on the NEXT update. This shim closes that
# one-release bootstrap gap from a unit that is already enabled everywhere.
#
# DELETE THIS BLOCK once every board in the field runs a runner >= 1.0.6.6:
# from then on both manifest generators enable the unit themselves and this is
# dead weight. Nothing else depends on it.
#
# ONE-TIME by design. The marker is written BEFORE the enable is attempted, so
# a refused or failing enable is never retried every boot, and a later
# `systemctl disable` by the operator is never overridden — the same
# «removed stays removed» rule the installer holds via sa02m_svc_apply.
# Cannot fail its caller: every step is guarded and it always returns 0.
DNS_ENSURE_UNIT=sa02m-dns-ensure.service
DNS_ENSURE_UNIT_FILE=/etc/systemd/system/sa02m-dns-ensure.service
DNS_BOOTSTRAP_MARKER=/var/lib/sa02m-net/dns-ensure-enabled.once
dns_ensure_bootstrap() {
    [ -f "$DNS_ENSURE_UNIT_FILE" ] || return 0
    [ -e "$DNS_BOOTSTRAP_MARKER" ] && return 0
    mkdir -p "$(dirname "$DNS_BOOTSTRAP_MARKER")" 2>/dev/null || true
    # `touch`, never `: >`. This script is #!/bin/sh and the board runs dash,
    # where `:` is a POSIX SPECIAL built-in: a redirection error on one aborts a
    # non-interactive shell outright, and NEITHER `2>/dev/null` NOR `|| true`
    # catches it. With the mkdir above failing (RO rootfs, ENOSPC, path
    # occupied) `: >` would kill this script at this line — no belt pass on the
    # first post-update boot, no `systemctl enable`, and the unit FAILED, which
    # breaks the `systemctl --failed` image gate. `touch` is a regular command,
    # so the same failure is an ordinary non-zero exit that `|| true` absorbs.
    # Same idiom as the grat-ARP marker in etc/fix-eth.sh.
    touch "$DNS_BOOTSTRAP_MARKER" 2>/dev/null || true
    # Only the never-enabled case. enabled/static/masked all mean "someone has
    # already decided" — leave every one of them exactly as it is.
    case "$(systemctl is-enabled "$DNS_ENSURE_UNIT" 2>/dev/null)" in
        disabled) ;;
        *) return 0 ;;
    esac
    if systemctl enable "$DNS_ENSURE_UNIT" >/dev/null 2>&1; then
        log "bootstrap: $DNS_ENSURE_UNIT enabled for the next boot (one-time)"
    else
        log "bootstrap: could not enable $DNS_ENSURE_UNIT (harmless — the belt still runs from here)"
    fi
    return 0
}

dns_ensure_bootstrap

for IFACE in eth0 eth1; do
    [ -d "/sys/class/net/$IFACE" ] || continue
    [ -f "/etc/network/interfaces.d/${IFACE}.conf" ] || continue

    carrier=$(cat "/sys/class/net/$IFACE/carrier" 2>/dev/null || echo 0)
    if [ "$carrier" = "1" ]; then
        log "$IFACE: carrier already up, skip"
        # This `continue` is BEFORE the `systemctl start fix-eth@` line below,
        # so on this path nothing else in the ladder ever runs — the resolver
        # belt has to be asserted here or not at all.
        dns_ensure "$IFACE"
        continue
    fi

    log "$IFACE: no carrier — soft PHY restart"
    ip link set "$IFACE" up 2>/dev/null || true
    sleep 1
    ethtool -r "$IFACE" 2>/dev/null || mii-tool -r "$IFACE" 2>/dev/null || true
    sleep 3

    carrier=$(cat "/sys/class/net/$IFACE/carrier" 2>/dev/null || echo 0)
    if [ "$carrier" != "1" ]; then
        ip link set "$IFACE" down 2>/dev/null || true
        sleep 1
        ip link set "$IFACE" up 2>/dev/null || true
        ethtool -r "$IFACE" 2>/dev/null || mii-tool -r "$IFACE" 2>/dev/null || true
        sleep 3
        carrier=$(cat "/sys/class/net/$IFACE/carrier" 2>/dev/null || echo 0)
    fi

    if [ "$carrier" = "1" ]; then
        log "$IFACE: link recovered after cold-boot fix"
    else
        log "$IFACE: still no carrier after cold-boot fix"
    fi
    dns_ensure "$IFACE"
    systemctl start --no-block "fix-eth@${IFACE}.service" 2>/dev/null || true
done
exit 0
