#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# 01-system.sh  •  Base OS, users, packages, serial symlinks
# ═══════════════════════════════════════════════════════════════════════════
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"
check_root

log INFO "=== [01] Системная настройка ==="

# ── Locale & timezone ──────────────────────────────────────────────────────
log INFO "Настройка локали и таймзоны"
locale-gen ru_RU.UTF-8 en_US.UTF-8 >> "$LOG_FILE" 2>&1 || true
update-locale LANG=ru_RU.UTF-8 >> "$LOG_FILE" 2>&1 || true
timedatectl set-timezone Europe/Moscow >> "$LOG_FILE" 2>&1 || true

# ── SSH: direct service mode instead of socket activation ──────────────────
ETC_REPO="$SCRIPT_DIR/../etc"
if [ -f "$ETC_REPO/sa02m-ssh-direct.sh" ]; then
    install -m 755 "$ETC_REPO/sa02m-ssh-direct.sh" /usr/local/sbin/sa02m-ssh-direct
    /usr/local/sbin/sa02m-ssh-direct >> "$LOG_FILE" 2>&1 || log WARN "Не удалось перевести SSH в direct service mode"
fi

SERIAL_PROFILE_CONF=/etc/sa02m_serial_profile.conf
if [ -n "${SA02M_SERIAL_PROFILE:-}" ]; then
    printf 'SA02M_SERIAL_PROFILE=%s\n' "$SA02M_SERIAL_PROFILE" > "$SERIAL_PROFILE_CONF"
    chmod 644 "$SERIAL_PROFILE_CONF"
    log INFO "Зафиксирован serial-профиль в $SERIAL_PROFILE_CONF: $SA02M_SERIAL_PROFILE"
elif [ ! -f "$SERIAL_PROFILE_CONF" ] && [ -f "$ETC_REPO/sa02m_serial_profile.conf" ]; then
    install -m 644 "$ETC_REPO/sa02m_serial_profile.conf" "$SERIAL_PROFILE_CONF"
    log INFO "Установлен шаблон $SERIAL_PROFILE_CONF"
fi

# ── Required packages ──────────────────────────────────────────────────────
log INFO "Установка пакетов"
apt-get update -qq >> "$LOG_FILE" 2>&1
pkg_install nginx fcgiwrap openssl net-tools psmisc exfatprogs

# ── User hmi ──────────────────────────────────────────────────────────────
if ! id hmi &>/dev/null; then
    log INFO "Создание пользователя hmi"
    useradd -m -s /bin/bash hmi >> "$LOG_FILE" 2>&1
fi

# ── Disable serial console getty ─────────────────────────────────────────
for tty in ttyS0 ttyS1; do
    systemctl disable "serial-getty@${tty}" 2>/dev/null || true
    systemctl mask    "serial-getty@${tty}" 2>/dev/null || true
done

# ── RS-485 / COM symlinks ──────────────────────────────────────────────────
SERIAL_PROFILE=$(sa02m_serial_profile)
BOARD_MODEL=$(sa02m_board_model)
read -r -a SERIAL_TARGETS <<< "$(sa02m_serial_targets "$SERIAL_PROFILE")"

log INFO "Профиль serial/RS-485: ${SERIAL_PROFILE} (model='${BOARD_MODEL:-unknown}')"
log INFO "Создание симлинков RS-485 / COM"

for stale_idx in 0 1 2 3 4; do
    rm -f "/dev/RS-485-${stale_idx}" "/dev/COM$(( stale_idx + 1 ))"
done

for idx in "${!SERIAL_TARGETS[@]}"; do
    tty="${SERIAL_TARGETS[$idx]}"
    com_idx=$(( idx + 1 ))
    for lnk in "RS-485-${idx}" "COM${com_idx}"; do
        target="/dev/${tty}"
        if [ -e "$target" ]; then
            ln -sf "$target" "/dev/$lnk"
            log OK "  /dev/$lnk → $target"
        else
            log WARN "  /dev/$lnk пропущен: $target отсутствует"
        fi
    done
done

# ── Persist symlinks via udev ─────────────────────────────────────────────
UDEV_RULE="/etc/udev/rules.d/99-sa02m-serial.rules"
{
    echo "# Generated by SA-02m installer"
    for idx in "${!SERIAL_TARGETS[@]}"; do
        tty="${SERIAL_TARGETS[$idx]}"
        com_idx=$(( idx + 1 ))
        echo "KERNEL==\"${tty}\", SYMLINK+=\"RS-485-${idx} COM${com_idx}\""
    done
} > "$UDEV_RULE"
udevadm control --reload-rules 2>/dev/null || true
write_sa02m_serial_map_conf /etc/sa02m_serial_map.conf
log INFO "Карта serial-портов записана в /etc/sa02m_serial_map.conf"

# ── USB / microSD: убрать устаревшую связку 99-local.rules + usb-mount@ ─────
OLD_LOCAL=/etc/udev/rules.d/99-local.rules
if [ -f "$OLD_LOCAL" ] && grep -q 'usb-mount@' "$OLD_LOCAL" 2>/dev/null; then
    grep -v 'usb-mount@' "$OLD_LOCAL" > /tmp/99-local.sa02m-strip.tmp 2>/dev/null || true
    if [ -s /tmp/99-local.sa02m-strip.tmp ]; then
        mv /tmp/99-local.sa02m-strip.tmp "$OLD_LOCAL"
        log INFO "Из $OLD_LOCAL удалены строки с usb-mount@"
    else
        rm -f "$OLD_LOCAL" /tmp/99-local.sa02m-strip.tmp
        log INFO "Удалён устаревший $OLD_LOCAL (правила usb-mount)"
    fi
    udevadm control --reload-rules 2>/dev/null || true
fi
if [ -f /etc/systemd/system/usb-mount@.service ]; then
    log INFO "Удаление устаревшего usb-mount@.service"
    systemctl list-units --no-pager --type=service 2>/dev/null \
        | grep -oE 'usb-mount@[^[:space:]]+\.service' | sort -u \
        | while read -r u; do systemctl stop "$u" 2>/dev/null || true; done
    rm -f /etc/systemd/system/usb-mount@.service
    systemctl daemon-reload >> "$LOG_FILE" 2>&1 || true
fi
if [ -f /usr/local/bin/usb-mount.sh ]; then
    log INFO "Удаление устаревшего /usr/local/bin/usb-mount.sh"
    rm -f /usr/local/bin/usb-mount.sh
fi

# ── USB / microSD: udev + storage-mount (exFAT при пустой ФС или NTFS) ─────
if [ -f "$ETC_REPO/storage-mount.sh" ]; then
    log INFO "Установка storage-mount (USB / microSD)"
    install -m 755 "$ETC_REPO/storage-mount.sh" /usr/local/bin/storage-mount.sh
    install -m 755 "$ETC_REPO/sa02m-set-storage-auto-format" /usr/local/sbin/sa02m-set-storage-auto-format
    install -m 644 "$ETC_REPO/systemd/storage-mount@.service" /etc/systemd/system/storage-mount@.service
    install -m 644 "$ETC_REPO/udev/99-storage.rules" /etc/udev/rules.d/99-storage.rules
    if [ ! -f /etc/sa02m_storage.conf ]; then
        install -m 644 "$ETC_REPO/sa02m_storage.conf" /etc/sa02m_storage.conf
    fi
    systemctl daemon-reload >> "$LOG_FILE" 2>&1 || true
    udevadm control --reload-rules 2>/dev/null || true
    log OK "storage-mount и udev 99-storage.rules установлены"
else
    log WARN "Нет $ETC_REPO/storage-mount.sh — пропуск установки съёмных носителей"
fi

# ── Mask unnecessary timers ────────────────────────────────────────────────
for unit in apt-daily.timer apt-daily-upgrade.timer; do
    systemctl mask "$unit" 2>/dev/null || true
done

log OK "=== [01] Системная настройка завершена ==="
