#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# 02-network.sh  •  Network interface config and fix-eth watchdog
# ═══════════════════════════════════════════════════════════════════════════
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"
check_root

log INFO "=== [02] Настройка сети ==="

: "${IP_ADDRESS:=$(sa02m_default_ip)}"
: "${NETMASK:=255.255.255.0}"
: "${GATEWAY:=$(sa02m_default_gw)}"
: "${DNS_SERVERS:=77.88.8.8 77.88.8.1}"
: "${NET_IFACE:=eth0}"

# ── /etc/network/interfaces ────────────────────────────────────────────────
log INFO "Создание /etc/network/interfaces"
cat > /etc/network/interfaces <<NET
# Generated by СА-02м installer
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback
NET

# ── eth0 static config ────────────────────────────────────────────────────
mkdir -p /etc/network/interfaces.d
log INFO "eth0 → $IP_ADDRESS / $NETMASK"

# На SA-02m-2 eth0 получает metric 200, чтобы eth1 DHCP (metric 100) был
# дефолтным маршрутом когда eth0 без кабеля (NO-CARRIER).
END0_METRIC_LINE=""
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ]; then
    END0_METRIC_LINE="    metric 200"
fi

cat > /etc/network/interfaces.d/eth0.conf <<END0
auto eth0
iface eth0 inet static
    address $IP_ADDRESS
    netmask $NETMASK
    gateway $GATEWAY
    dns-nameservers $DNS_SERVERS
${END0_METRIC_LINE}
END0

# ── eth1 DHCP config for SA-02m-2 (2-eth) ────────────────────────────────
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ] && [ ! -f /etc/network/interfaces.d/eth1.conf ]; then
    cat > /etc/network/interfaces.d/eth1.conf <<'END1'
allow-hotplug eth1
iface eth1 inet dhcp
    metric 100
    post-up ip route replace default via 192.168.1.1 dev eth1 metric 100 || true
END1
    log OK "eth1 DHCP конфиг создан"
fi

# ── eth1 DHCP: принудительный default route при RFC3442 (option 121) ─────────
# Некоторые DHCP-серверы шлют option 121 (classless static routes), что заставляет
# dhclient-script игнорировать option 3 (routers) согласно RFC3442.
# Хук гарантирует, что default route через DHCP-шлюз будет применён всегда.
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ]; then
    mkdir -p /etc/dhcp/dhclient-exit-hooks.d
    cat > /etc/dhcp/dhclient-exit-hooks.d/eth1-default-route <<'HOOK'
#!/bin/sh
if [ "$interface" = "eth1" ] && [ -n "$new_routers" ]; then
    case "$reason" in
        BOUND|RENEW|REBIND|REBOOT)
            ip route replace default via $new_routers dev eth1 metric 100 2>/dev/null || true
            ;;
    esac
fi
HOOK
    chmod 755 /etc/dhcp/dhclient-exit-hooks.d/eth1-default-route
    log OK "dhclient exit hook для eth1 default route установлен"
fi

# ── Network watchdog deployment ────────────────────────────────────────────
ETC_DIR="$SCRIPT_DIR/../etc"

if [ -f "$ETC_DIR/sa02m-eth-led-lib.sh" ]; then
    log INFO "Установка sa02m-eth-led-lib.sh"
    mkdir -p /usr/local/lib
    install -m 644 "$ETC_DIR/sa02m-eth-led-lib.sh" /usr/local/lib/sa02m-eth-led-lib.sh
fi

if [ -f "$ETC_DIR/sa02m-eth0-led.sh" ]; then
    log INFO "Установка sa02m-eth0-led.sh"
    install -m 755 "$ETC_DIR/sa02m-eth0-led.sh" /usr/local/bin/sa02m-eth0-led.sh
fi

if [ -f "$ETC_DIR/fix-eth.sh" ]; then
    log INFO "Установка fix-eth.sh"
    install -m 755 "$ETC_DIR/fix-eth.sh" /usr/local/bin/fix-eth.sh
fi

if [ -f "$ETC_DIR/net-watchdog.sh" ]; then
    log INFO "Установка net-watchdog.sh"
    install -m 755 "$ETC_DIR/net-watchdog.sh" /usr/local/bin/net-watchdog.sh
fi

if [ -f "$ETC_DIR/inet-failover.sh" ]; then
    log INFO "Установка inet-failover.sh"
    install -m 755 "$ETC_DIR/inet-failover.sh" /usr/local/bin/inet-failover.sh
fi

if [ -f "$ETC_DIR/fix-eth.service" ]; then
    log INFO "Установка fix-eth.service"
    install -m 644 "$ETC_DIR/fix-eth.service" /etc/systemd/system/fix-eth.service
fi

if [ -f "$ETC_DIR/fix-eth@.service" ]; then
    log INFO "Установка fix-eth@.service"
    install -m 644 "$ETC_DIR/fix-eth@.service" /etc/systemd/system/fix-eth@.service
fi

if [ -f "$ETC_DIR/net-watchdog.service" ]; then
    log INFO "Установка net-watchdog.service"
    install -m 644 "$ETC_DIR/net-watchdog.service" /etc/systemd/system/net-watchdog.service
fi

if [ -f "$ETC_DIR/sa02m-eth0-led-poll.sh" ]; then
    log INFO "Установка sa02m-eth0-led-poll.sh"
    install -m 755 "$ETC_DIR/sa02m-eth0-led-poll.sh" /usr/local/bin/sa02m-eth0-led-poll.sh
fi

if [ -f "$ETC_DIR/systemd/sa02m-eth0-led-poll.service" ]; then
    log INFO "Установка sa02m-eth0-led-poll.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-eth0-led-poll.service" /etc/systemd/system/sa02m-eth0-led-poll.service
fi

if [ -f "$ETC_DIR/99-lan-recovery.rules" ]; then
    log INFO "Установка udev правил"
    install -m 644 "$ETC_DIR/99-lan-recovery.rules" /etc/udev/rules.d/
fi

# Шаблон конфига watchdog (только если ещё не существует — не затираем пользовательский)
if [ -f "$ETC_DIR/sa02m_network.conf" ] && [ ! -f /etc/sa02m_network.conf ]; then
    log INFO "Создание /etc/sa02m_network.conf (шаблон)"
    install -m 644 "$ETC_DIR/sa02m_network.conf" /etc/sa02m_network.conf
fi

if [ -f "$ETC_DIR/sa02m-eth1-coldboot.sh" ]; then
    log INFO "Установка sa02m-eth1-coldboot.sh"
    install -m 755 "$ETC_DIR/sa02m-eth1-coldboot.sh" /usr/local/bin/sa02m-eth1-coldboot.sh
fi

if [ -f "$ETC_DIR/systemd/sa02m-eth1-coldboot.service" ]; then
    log INFO "Установка sa02m-eth1-coldboot.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-eth1-coldboot.service" \
        /etc/systemd/system/sa02m-eth1-coldboot.service
fi

if [ -f "$ETC_DIR/fix-eth1-internet.sh" ]; then
    log INFO "Установка fix-eth1-internet.sh"
    install -m 755 "$ETC_DIR/fix-eth1-internet.sh" /usr/local/sbin/fix-eth1-internet.sh
fi

# Remove legacy phy-coldboot service if still present on this system
if [ -f /etc/systemd/system/sa02m-phy-coldboot.service ]; then
    systemctl stop sa02m-phy-coldboot 2>/dev/null || true
    systemctl disable sa02m-phy-coldboot 2>/dev/null || true
    rm -f /etc/systemd/system/sa02m-phy-coldboot.service
    log INFO "Удалён устаревший sa02m-phy-coldboot.service"
fi
rm -f /usr/local/bin/sa02m-phy-coldboot.sh

# ── Заводские имена интерфейсов (eth0/eth1) ───────────────────────────────
# Kernel SA-02m (5.10.35) по умолчанию выдаёт `eth0` (sun4i-emac,
# 1c0b000.ethernet) и `eth1` (dwmac-sun8i, 1c50000.ethernet). Мы НЕ используем
# systemd `.link` файлы для переименования (`end0`/`end1`), потому что после
# обновления systemd/udev эти правила могут потерять эффект (или конфликтовать
# со встроенными Debian generators) → сеть слетает. Все сервисы, LED-polling,
# DHCP hooks и `/etc/network/interfaces.d/*.conf` работают с kernel-именами.
# На всякий случай удаляем legacy `.link` файлы от предыдущих версий образа.
rm -f /etc/systemd/network/10-end0.link /etc/systemd/network/10-end1.link \
      /etc/systemd/network/10-eth0.link /etc/systemd/network/10-eth1.link 2>/dev/null || true
log INFO "Используются заводские имена интерфейсов kernel (eth0/eth1)"

# ── nftables: kernel-aware ────────────────────────────────────────────────
# С 1.0.4.x kernel SA-02m (5.10.35) собран с CONFIG_NF_TABLES=y — nftables
# работает штатно. На старом kernel (5.10.35-sa02m+ без NF_TABLES) сервис
# фейлил с "Netlink socket: Protocol not supported" → маскировали. Проверяем
# и снимаем/накидываем маску в зависимости от возможностей ядра.
if grep -qE '^CONFIG_NF_TABLES=[ym]' "/boot/config-$(uname -r)" 2>/dev/null; then
    systemctl unmask nftables.service >>"$LOG_FILE" 2>&1 || true
    log INFO "nftables.service unmasked (kernel с CONFIG_NF_TABLES)"
else
    systemctl mask nftables.service >>"$LOG_FILE" 2>&1 || true
    log INFO "nftables.service masked (kernel без CONFIG_NF_TABLES)"
fi

systemctl daemon-reload
udevadm control --reload-rules 2>/dev/null || true

# Ключевой сервис для ifupdown: без него /etc/network/interfaces.d/*.conf
# не применяется при boot. На чистом Debian bullseye после debootstrap
# --variant=minbase preset не всегда включён — включаем явно.
svc_enable networking

svc_enable net-watchdog
svc_enable sa02m-eth1-coldboot
svc_enable sa02m-eth0-led-poll
log OK "Network watchdog активирован"

# ── Apply now ─────────────────────────────────────────────────────────────
if [ -z "${SA02M_ROOTFS_BUILD:-}" ]; then
    log INFO "Поднимаем $NET_IFACE"
    ip link set "$NET_IFACE" up 2>/dev/null || true
    ip addr flush dev "$NET_IFACE" 2>/dev/null || true
    ifup "$NET_IFACE" >> "$LOG_FILE" 2>&1 || true
fi

log OK "=== [02] Сеть настроена: $IP_ADDRESS ==="
