#!/bin/bash
set -o pipefail  # catch masked failures in pipes (Y7); set -u deferred pending on-device install test
# ═══════════════════════════════════════════════════════════════════════════
# 02-network.sh  •  Network interface config and fix-eth watchdog
# ═══════════════════════════════════════════════════════════════════════════
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"
check_root

log INFO "=== [02] Настройка сети ==="

# Detect the real interface names on this board. Field devices split between the
# kernel scheme (eth0/eth1) and the predictable-names scheme (end0/end1); the
# installer must act on whatever actually exists in /sys/class/net rather than
# hardcode eth0 (which is inert on an end0 board — see status.cgi bridge).
LAN0=$(first_existing_iface eth0 end0)
LAN1=$(first_existing_iface eth1 end1)

: "${IP_ADDRESS:=$(sa02m_default_ip)}"
: "${NETMASK:=255.255.255.0}"
: "${GATEWAY:=$(sa02m_default_gw)}"
: "${DNS_SERVERS:=77.88.8.8 77.88.8.1}"
: "${NET_IFACE:=$LAN0}"

# ── /etc/network/interfaces ────────────────────────────────────────────────
log INFO "Создание /etc/network/interfaces"
cat > /etc/network/interfaces <<NET
# Generated by СА-02м installer
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback
NET

# ── LAN0 static config ────────────────────────────────────────────────────
mkdir -p /etc/network/interfaces.d
log INFO "$LAN0 → $IP_ADDRESS / $NETMASK"

# На SA-02m-2 LAN0 получает metric 200, чтобы LAN1 DHCP (metric 100) был
# дефолтным маршрутом когда LAN0 без кабеля (NO-CARRIER).
END0_METRIC_LINE=""
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ]; then
    END0_METRIC_LINE="    metric 200"
fi

# Idempotency: only (re)write $LAN0.conf on first install (file absent) or when
# --ip was passed explicitly. A plain re-run of the installer (the upgrade path)
# must NOT clobber a static IP the operator set later via the web UI — doing so
# resets the device to the factory address and makes it unreachable.
# LAN0_CONF_WRITTEN gates the "Apply now" flush below: we disturb the live
# interface ONLY when this run actually (re)wrote the config.
LAN0_CONF_WRITTEN=0
if [ ! -f "/etc/network/interfaces.d/$LAN0.conf" ] || [ "${IP_EXPLICIT:-0}" = "1" ]; then
cat > "/etc/network/interfaces.d/$LAN0.conf" <<END0
auto $LAN0
iface $LAN0 inet static
    address $IP_ADDRESS
    netmask $NETMASK
    gateway $GATEWAY
    dns-nameservers $DNS_SERVERS
${END0_METRIC_LINE}
END0
    LAN0_CONF_WRITTEN=1
else
    echo "$LAN0.conf exists and --ip not given — preserving operator IP" >&2
fi

# ── LAN1 DHCP config for SA-02m-2 (2-eth) ────────────────────────────────
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ] && [ ! -f "/etc/network/interfaces.d/$LAN1.conf" ]; then
    cat > "/etc/network/interfaces.d/$LAN1.conf" <<END1
allow-hotplug $LAN1
iface $LAN1 inet dhcp
    metric 100
    post-up ip route replace default via 192.168.1.1 dev $LAN1 metric 100 || true
END1
    log OK "$LAN1 DHCP конфиг создан"
fi

# ── eth1 DHCP: принудительный default route при RFC3442 (option 121) ─────────
# Некоторые DHCP-серверы шлют option 121 (classless static routes), что заставляет
# dhclient-script игнорировать option 3 (routers) согласно RFC3442.
# Хук гарантирует, что default route через DHCP-шлюз будет применён всегда.
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ]; then
    mkdir -p /etc/dhcp/dhclient-exit-hooks.d
    # Unquoted heredoc so $LAN1 expands to the real interface name; the runtime
    # dhclient vars ($interface/$new_routers/$reason) are escaped to stay literal.
    cat > /etc/dhcp/dhclient-exit-hooks.d/eth1-default-route <<HOOK
#!/bin/sh
if [ "\$interface" = "$LAN1" ] && [ -n "\$new_routers" ]; then
    case "\$reason" in
        BOUND|RENEW|REBIND|REBOOT)
            ip route replace default via \$new_routers dev $LAN1 metric 100 2>/dev/null || true
            ;;
    esac
fi
HOOK
    chmod 755 /etc/dhcp/dhclient-exit-hooks.d/eth1-default-route
    log OK "dhclient exit hook для $LAN1 default route установлен"
fi

# ── Network watchdog deployment ────────────────────────────────────────────
ETC_DIR="$SCRIPT_DIR/../etc"

if [ -f "$ETC_DIR/sa02m-eth-led-lib.sh" ]; then
    log INFO "Установка sa02m-eth-led-lib.sh"
    mkdir -p /usr/local/lib
    install -m 644 "$ETC_DIR/sa02m-eth-led-lib.sh" /usr/local/lib/sa02m-eth-led-lib.sh
fi

if [ -f "$ETC_DIR/sa02m-eth0-led.sh" ]; then
    log INFO "Установка sa02m-eth0-led.sh"
    install -m 755 "$ETC_DIR/sa02m-eth0-led.sh" /usr/local/bin/sa02m-eth0-led.sh
fi

if [ -f "$ETC_DIR/fix-eth.sh" ]; then
    log INFO "Установка fix-eth.sh"
    install -m 755 "$ETC_DIR/fix-eth.sh" /usr/local/bin/fix-eth.sh
fi

if [ -f "$ETC_DIR/net-watchdog.sh" ]; then
    log INFO "Установка net-watchdog.sh"
    install -m 755 "$ETC_DIR/net-watchdog.sh" /usr/local/bin/net-watchdog.sh
fi

if [ -f "$ETC_DIR/inet-failover.sh" ]; then
    log INFO "Установка inet-failover.sh"
    install -m 755 "$ETC_DIR/inet-failover.sh" /usr/local/bin/inet-failover.sh
fi

if [ -f "$ETC_DIR/fix-eth.service" ]; then
    log INFO "Установка fix-eth.service"
    install -m 644 "$ETC_DIR/fix-eth.service" /etc/systemd/system/fix-eth.service
fi

if [ -f "$ETC_DIR/fix-eth@.service" ]; then
    log INFO "Установка fix-eth@.service"
    install -m 644 "$ETC_DIR/fix-eth@.service" /etc/systemd/system/fix-eth@.service
fi

if [ -f "$ETC_DIR/net-watchdog.service" ]; then
    log INFO "Установка net-watchdog.service"
    install -m 644 "$ETC_DIR/net-watchdog.service" /etc/systemd/system/net-watchdog.service
fi

if [ -f "$ETC_DIR/sa02m-eth0-led-poll.sh" ]; then
    log INFO "Установка sa02m-eth0-led-poll.sh"
    install -m 755 "$ETC_DIR/sa02m-eth0-led-poll.sh" /usr/local/bin/sa02m-eth0-led-poll.sh
fi

if [ -f "$ETC_DIR/systemd/sa02m-eth0-led-poll.service" ]; then
    log INFO "Установка sa02m-eth0-led-poll.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-eth0-led-poll.service" /etc/systemd/system/sa02m-eth0-led-poll.service
fi

if [ -f "$ETC_DIR/99-lan-recovery.rules" ]; then
    log INFO "Установка udev правил"
    install -m 644 "$ETC_DIR/99-lan-recovery.rules" /etc/udev/rules.d/
fi

# Шаблон конфига watchdog (только если ещё не существует — не затираем пользовательский)
if [ -f "$ETC_DIR/sa02m_network.conf" ] && [ ! -f /etc/sa02m_network.conf ]; then
    log INFO "Создание /etc/sa02m_network.conf (шаблон)"
    install -m 644 "$ETC_DIR/sa02m_network.conf" /etc/sa02m_network.conf
fi

if [ -f "$ETC_DIR/sa02m-eth1-coldboot.sh" ]; then
    log INFO "Установка sa02m-eth1-coldboot.sh"
    install -m 755 "$ETC_DIR/sa02m-eth1-coldboot.sh" /usr/local/bin/sa02m-eth1-coldboot.sh
fi

if [ -f "$ETC_DIR/systemd/sa02m-eth1-coldboot.service" ]; then
    log INFO "Установка sa02m-eth1-coldboot.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-eth1-coldboot.service" \
        /etc/systemd/system/sa02m-eth1-coldboot.service
fi

if [ -f "$ETC_DIR/fix-eth1-internet.sh" ]; then
    log INFO "Установка fix-eth1-internet.sh"
    install -m 755 "$ETC_DIR/fix-eth1-internet.sh" /usr/local/sbin/fix-eth1-internet.sh
fi

# Remove legacy phy-coldboot service if still present on this system
if [ -f /etc/systemd/system/sa02m-phy-coldboot.service ]; then
    systemctl stop sa02m-phy-coldboot 2>/dev/null || true
    systemctl disable sa02m-phy-coldboot 2>/dev/null || true
    rm -f /etc/systemd/system/sa02m-phy-coldboot.service
    log INFO "Удалён устаревший sa02m-phy-coldboot.service"
fi
rm -f /usr/local/bin/sa02m-phy-coldboot.sh

# ── Имена интерфейсов — не переименовывать работающий линк ─────────────────
# Board split: часть устройств на kernel-именах (`eth0`/`eth1`, sun4i-emac +
# dwmac-sun8i), часть — на predictable-names (`end0`/`end1`). Мы НЕ используем
# systemd `.link` файлы для форсирования имён, потому что после обновления
# systemd/udev эти правила могут потерять эффект → сеть слетает.
# ПРАВИЛО БЕЗОПАСНОСТИ: никогда не переименовываем интерфейс, который сейчас в
# работе. Legacy `end*.link` файлы удаляем ТОЛЬКО на eth-плате (где рабочее имя
# — eth0, а `end*.link` — мусор от старого образа). На end-плате `end*.link`
# может как раз и давать рабочее имя `end0` — трогать нельзя.
rm -f /etc/systemd/network/10-eth0.link /etc/systemd/network/10-eth1.link 2>/dev/null || true
if [ "$LAN0" = "eth0" ]; then
    rm -f /etc/systemd/network/10-end0.link /etc/systemd/network/10-end1.link 2>/dev/null || true
    log INFO "Используются заводские имена интерфейсов kernel ($LAN0/$LAN1)"
else
    log INFO "Обнаружена схема predictable-names ($LAN0/$LAN1) — .link файлы не трогаем"
fi

# ── nftables: kernel-aware ────────────────────────────────────────────────
# С 1.0.4.x kernel SA-02m (5.10.35) собран с CONFIG_NF_TABLES=y — nftables
# работает штатно. На старом kernel (5.10.35-sa02m+ без NF_TABLES) сервис
# фейлил с "Netlink socket: Protocol not supported" → маскировали. Проверяем
# и снимаем/накидываем маску в зависимости от возможностей ядра.
if grep -qE '^CONFIG_NF_TABLES=[ym]' "/boot/config-$(uname -r)" 2>/dev/null; then
    systemctl unmask nftables.service >>"$LOG_FILE" 2>&1 || true
    log INFO "nftables.service unmasked (kernel с CONFIG_NF_TABLES)"
else
    systemctl mask nftables.service >>"$LOG_FILE" 2>&1 || true
    log INFO "nftables.service masked (kernel без CONFIG_NF_TABLES)"
fi

systemctl daemon-reload >/dev/null 2>&1 || true
udevadm control --reload-rules 2>/dev/null || true

# Ключевой сервис для ifupdown: без него /etc/network/interfaces.d/*.conf
# не применяется при boot. На чистом Debian bullseye после debootstrap
# --variant=minbase preset не всегда включён — включаем явно.
svc_enable networking

svc_enable net-watchdog
svc_enable sa02m-eth1-coldboot
svc_enable sa02m-eth0-led-poll
log OK "Network watchdog активирован"

# ── Apply now ─────────────────────────────────────────────────────────────
# Flush + ifup ONLY when this run actually (re)wrote $LAN0.conf. On a plain
# re-run that preserved an existing config the interface is already up with the
# operator's IP — flushing it would drop the live management link (SSH). Skip in
# rootfs build (no live interface to apply).
if [ -z "${SA02M_ROOTFS_BUILD:-}" ] && [ "$LAN0_CONF_WRITTEN" = "1" ]; then
    log INFO "Поднимаем $NET_IFACE"
    ip link set "$NET_IFACE" up 2>/dev/null || true
    ip addr flush dev "$NET_IFACE" 2>/dev/null || true
    ifup "$NET_IFACE" >> "$LOG_FILE" 2>&1 || true
elif [ -z "${SA02M_ROOTFS_BUILD:-}" ]; then
    log INFO "$NET_IFACE: конфиг сохранён без изменений — не трогаем живой интерфейс"
fi

log OK "=== [02] Сеть настроена: $IP_ADDRESS ==="
