#!/bin/bash
set -o pipefail  # catch masked failures in pipes (Y7); set -u deferred pending on-device install test
# ═══════════════════════════════════════════════════════════════════════════
# 02-network.sh  •  Network interface config and fix-eth watchdog
# ═══════════════════════════════════════════════════════════════════════════
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"
check_root
ETC_DIR="$SCRIPT_DIR/../etc"

log INFO "=== [02] Настройка сети ==="

# ── Канонические имена интерфейсов (eth0/eth1) ────────────────────────────
# Installed BEFORE the detection below: an opt-in live rename must already be
# reflected in LAN0/LAN1, otherwise those names are stale for the whole run.
# Contract: docs/contracts/ethernet-iface-naming.md
if [ -f "$ETC_DIR/sa02m-iface-canonical.sh" ]; then
    log INFO "Установка sa02m-iface-canonical.sh"
    install -m 755 "$ETC_DIR/sa02m-iface-canonical.sh" /usr/local/sbin/sa02m-iface-canonical.sh
fi

if [ -f "$ETC_DIR/systemd/sa02m-iface-canonical.service" ]; then
    log INFO "Установка sa02m-iface-canonical.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-iface-canonical.service" \
        /etc/systemd/system/sa02m-iface-canonical.service
fi

# Renaming a LIVE interface drops the management link (SSH), and the idempotency
# note further down already encodes "a plain re-run must never disturb the live
# interface". So the rename is DEFERRED to the next boot by default;
# SA02M_CANONICAL_IFACE_NOW=1 (install.sh --canonical-iface-now) opts in.
CANONICAL_RENAME_OK=0
if [ "${SA02M_CANONICAL_IFACE_NOW:-0}" = "1" ] && [ -z "${SA02M_ROOTFS_BUILD:-}" ] \
   && [ -x /usr/local/sbin/sa02m-iface-canonical.sh ]; then
    log INFO "SA02M_CANONICAL_IFACE_NOW=1 — переименовываем интерфейсы сейчас"
    if /usr/local/sbin/sa02m-iface-canonical.sh --live >> "$LOG_FILE" 2>&1; then
        CANONICAL_RENAME_OK=1
        log OK "Имена интерфейсов канонизированы"
    else
        log WARN "Переименование не выполнено — см. /var/log/sa02m-iface-canonical.log"
    fi
fi

# Detect the real interface names on this board. Field devices split between the
# kernel scheme (eth0/eth1) and the predictable-names scheme (end0/end1); the
# installer must act on whatever actually exists in /sys/class/net rather than
# hardcode eth0 (which is inert on an end0 board — see status.cgi bridge).
LAN0=$(first_existing_iface eth0 end0)
LAN1=$(first_existing_iface eth1 end1)

: "${IP_ADDRESS:=$(sa02m_default_ip)}"
: "${NETMASK:=255.255.255.0}"
: "${GATEWAY:=$(sa02m_default_gw)}"
: "${DNS_SERVERS:=77.88.8.8 77.88.8.1}"
: "${NET_IFACE:=$LAN0}"

# ── /etc/network/interfaces ────────────────────────────────────────────────
log INFO "Создание /etc/network/interfaces"
# The .conf filter is LOAD-BEARING: backups and debris in interfaces.d
# (<conf>.sa02m-bak from the panel/migration, editor droppings) must stay
# INERT. A bare `*` sources them as live config — a backed-up duplicate
# `auto eth0` stanza makes `ifup -a` configure eth0 twice -> the second
# `ip addr add` fails with "RTNETLINK: File exists" -> networking FAILED
# (bench-confirmed 2026-07-29). This unconditional rewrite of
# /etc/network/interfaces is itself the field migration for boards that
# still carry the wide glob.
cat > /etc/network/interfaces <<NET
# Generated by СА-02м installer
source /etc/network/interfaces.d/*.conf

auto lo
iface lo inet loopback
NET

# ── LAN0 static config ────────────────────────────────────────────────────
mkdir -p /etc/network/interfaces.d
log INFO "$LAN0 → $IP_ADDRESS / $NETMASK"

# На SA-02m-2 LAN0 получает metric 200, чтобы LAN1 DHCP (metric 100) был
# дефолтным маршрутом когда LAN0 без кабеля (NO-CARRIER).
END0_METRIC_LINE=""
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ]; then
    END0_METRIC_LINE="    metric 200"
fi

# Idempotency: only (re)write $LAN0.conf on first install (file absent) or when
# --ip was passed explicitly. A plain re-run of the installer (the upgrade path)
# must NOT clobber a static IP the operator set later via the web UI — doing so
# resets the device to the factory address and makes it unreachable.
# LAN0_CONF_WRITTEN gates the "Apply now" flush below: we disturb the live
# interface ONLY when this run actually (re)wrote the config.
LAN0_CONF_WRITTEN=0
if [ ! -f "/etc/network/interfaces.d/$LAN0.conf" ] || [ "${IP_EXPLICIT:-0}" = "1" ]; then
cat > "/etc/network/interfaces.d/$LAN0.conf" <<END0
auto $LAN0
iface $LAN0 inet static
    address $IP_ADDRESS
    netmask $NETMASK
    gateway $GATEWAY
    dns-nameservers $DNS_SERVERS
${END0_METRIC_LINE}
END0
    LAN0_CONF_WRITTEN=1
else
    echo "$LAN0.conf exists and --ip not given — preserving operator IP" >&2
fi

# ── LAN1 DHCP config for SA-02m-2 (2-eth) ────────────────────────────────
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ] && [ ! -f "/etc/network/interfaces.d/$LAN1.conf" ]; then
    cat > "/etc/network/interfaces.d/$LAN1.conf" <<END1
allow-hotplug $LAN1
iface $LAN1 inet dhcp
    metric 100
    post-up ip route replace default via 192.168.1.1 dev $LAN1 metric 100 || true
END1
    log OK "$LAN1 DHCP конфиг создан"
fi

# ── eth1 DHCP: принудительный default route при RFC3442 (option 121) ─────────
# Некоторые DHCP-серверы шлют option 121 (classless static routes), что заставляет
# dhclient-script игнорировать option 3 (routers) согласно RFC3442.
# Хук гарантирует, что default route через DHCP-шлюз будет применён всегда.
if [ "$(sa02m_hw_variant)" = "sa02m-2eth" ]; then
    mkdir -p /etc/dhcp/dhclient-exit-hooks.d
    # Unquoted heredoc so $LAN1 expands to the real interface name; the runtime
    # dhclient vars ($interface/$new_routers/$reason) are escaped to stay literal.
    cat > /etc/dhcp/dhclient-exit-hooks.d/eth1-default-route <<HOOK
#!/bin/sh
if [ "\$interface" = "$LAN1" ] && [ -n "\$new_routers" ]; then
    case "\$reason" in
        BOUND|RENEW|REBIND|REBOOT)
            ip route replace default via \$new_routers dev $LAN1 metric 100 2>/dev/null || true
            ;;
    esac
fi
HOOK
    chmod 755 /etc/dhcp/dhclient-exit-hooks.d/eth1-default-route
    log OK "dhclient exit hook для $LAN1 default route установлен"
fi

# ── dhclient: advertise the system hostname over DHCP (option 12) ───────────
# Routers label the device by its host name only if dhclient sends option 12.
# Non-destructive + idempotent: keep the package-default request list, add the
# directive once. Covers every default-conf dhclient path (eth0-if-DHCP via the
# web panel, eth1 DHCP on 2-eth, USB CDC-ethernet modem). Inert on a factory
# 1-eth device where eth0 is STATIC (no DHCP transaction — documented limit).
DHCLIENT_CONF=/etc/dhcp/dhclient.conf
if [ -z "${SA02M_ROOTFS_BUILD:-}" ] || [ -f "$DHCLIENT_CONF" ]; then
    mkdir -p /etc/dhcp
    if [ ! -f "$DHCLIENT_CONF" ]; then
        printf '# SA-02m: send hostname (DHCP option 12)\nsend host-name = gethostname();\n' > "$DHCLIENT_CONF"
        chmod 644 "$DHCLIENT_CONF"
        log OK "dhclient.conf создан: send host-name (option 12)"
    elif ! grep -qE '^[[:space:]]*send[[:space:]]+host-name' "$DHCLIENT_CONF"; then
        printf '\n# SA-02m: send hostname (DHCP option 12)\nsend host-name = gethostname();\n' >> "$DHCLIENT_CONF"
        log OK "dhclient.conf: добавлен send host-name (option 12)"
    fi
fi

# ── Network watchdog deployment ────────────────────────────────────────────
if [ -f "$ETC_DIR/sa02m-eth-led-lib.sh" ]; then
    log INFO "Установка sa02m-eth-led-lib.sh"
    mkdir -p /usr/local/lib
    install -m 644 "$ETC_DIR/sa02m-eth-led-lib.sh" /usr/local/lib/sa02m-eth-led-lib.sh
fi

if [ -f "$ETC_DIR/sa02m-eth0-led.sh" ]; then
    log INFO "Установка sa02m-eth0-led.sh"
    install -m 755 "$ETC_DIR/sa02m-eth0-led.sh" /usr/local/bin/sa02m-eth0-led.sh
fi

if [ -f "$ETC_DIR/fix-eth.sh" ]; then
    log INFO "Установка fix-eth.sh"
    install -m 755 "$ETC_DIR/fix-eth.sh" /usr/local/bin/fix-eth.sh
fi

if [ -f "$ETC_DIR/net-watchdog.sh" ]; then
    log INFO "Установка net-watchdog.sh"
    install -m 755 "$ETC_DIR/net-watchdog.sh" /usr/local/bin/net-watchdog.sh
fi

if [ -f "$ETC_DIR/inet-failover.sh" ]; then
    log INFO "Установка inet-failover.sh"
    install -m 755 "$ETC_DIR/inet-failover.sh" /usr/local/bin/inet-failover.sh
fi

if [ -f "$ETC_DIR/fix-eth.service" ]; then
    log INFO "Установка fix-eth.service"
    install -m 644 "$ETC_DIR/fix-eth.service" /etc/systemd/system/fix-eth.service
fi

if [ -f "$ETC_DIR/fix-eth@.service" ]; then
    log INFO "Установка fix-eth@.service"
    install -m 644 "$ETC_DIR/fix-eth@.service" /etc/systemd/system/fix-eth@.service
fi

if [ -f "$ETC_DIR/net-watchdog.service" ]; then
    log INFO "Установка net-watchdog.service"
    install -m 644 "$ETC_DIR/net-watchdog.service" /etc/systemd/system/net-watchdog.service
fi

if [ -f "$ETC_DIR/sa02m-eth0-led-poll.sh" ]; then
    log INFO "Установка sa02m-eth0-led-poll.sh"
    install -m 755 "$ETC_DIR/sa02m-eth0-led-poll.sh" /usr/local/bin/sa02m-eth0-led-poll.sh
fi

if [ -f "$ETC_DIR/systemd/sa02m-eth0-led-poll.service" ]; then
    log INFO "Установка sa02m-eth0-led-poll.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-eth0-led-poll.service" /etc/systemd/system/sa02m-eth0-led-poll.service
fi

if [ -f "$ETC_DIR/99-lan-recovery.rules" ]; then
    log INFO "Установка udev правил"
    install -m 644 "$ETC_DIR/99-lan-recovery.rules" /etc/udev/rules.d/
fi

# Mechanism-4 retry (contract §1.0): the udev rule retriggers the convergent
# rename script on every end* add/move; the retry unit is event-driven only
# (no enable — it has no [Install]). The file-wide `udevadm control
# --reload-rules` + daemon-reload at the end of this script cover both.
if [ -f "$ETC_DIR/98-sa02m-iface-canonical.rules" ]; then
    log INFO "Установка 98-sa02m-iface-canonical.rules (событийный retry канонизации)"
    install -m 644 "$ETC_DIR/98-sa02m-iface-canonical.rules" /etc/udev/rules.d/
fi
if [ -f "$ETC_DIR/systemd/system/sa02m-iface-canonical-retry.service" ]; then
    log INFO "Установка sa02m-iface-canonical-retry.service"
    install -m 644 "$ETC_DIR/systemd/system/sa02m-iface-canonical-retry.service" \
        /etc/systemd/system/sa02m-iface-canonical-retry.service
fi

# Шаблон конфига watchdog (только если ещё не существует — не затираем пользовательский)
if [ -f "$ETC_DIR/sa02m_network.conf" ] && [ ! -f /etc/sa02m_network.conf ]; then
    log INFO "Создание /etc/sa02m_network.conf (шаблон)"
    install -m 644 "$ETC_DIR/sa02m_network.conf" /etc/sa02m_network.conf
fi

# Script home is usr/local/sbin/ in the repo (NOT etc/), and the unit's
# ExecStart is /usr/local/sbin/ — the old etc/-sourced, /usr/local/bin/-targeted
# block was a dead guard (never fired), so the unit hit 203/EXEC the moment
# eth1.conf first existed (exposed by the canonical-naming bench run).
if [ -f "$ETC_DIR/../usr/local/sbin/sa02m-eth1-coldboot.sh" ]; then
    log INFO "Установка sa02m-eth1-coldboot.sh"
    install -m 755 "$ETC_DIR/../usr/local/sbin/sa02m-eth1-coldboot.sh" \
        /usr/local/sbin/sa02m-eth1-coldboot.sh
fi

if [ -f "$ETC_DIR/systemd/sa02m-eth1-coldboot.service" ]; then
    log INFO "Установка sa02m-eth1-coldboot.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-eth1-coldboot.service" \
        /etc/systemd/system/sa02m-eth1-coldboot.service
fi

# eth0+eth1 soft PHY cold-boot (replaces eth1-only path for LAN0 first-boot link).
if [ -f "$ETC_DIR/../usr/local/sbin/sa02m-eth-coldboot.sh" ]; then
    log INFO "Установка sa02m-eth-coldboot.sh"
    install -m 755 "$ETC_DIR/../usr/local/sbin/sa02m-eth-coldboot.sh" \
        /usr/local/sbin/sa02m-eth-coldboot.sh
fi
if [ -f "$ETC_DIR/systemd/sa02m-eth-coldboot.service" ]; then
    log INFO "Установка sa02m-eth-coldboot.service"
    install -m 644 "$ETC_DIR/systemd/sa02m-eth-coldboot.service" \
        /etc/systemd/system/sa02m-eth-coldboot.service
fi

# ── Загрузка без DNS: ожидание carrier + пересборка резолвера ─────────────
# Контракт: docs/contracts/boot-network-dns.md. Оба хелпера идемпотентны и
# всегда выходят с кодом 0; drop-in'ы подключены через `ExecStartPre=-`, так
# что ни один из них не может уронить ifup@ или networking.
if [ -f "$ETC_DIR/../usr/local/sbin/sa02m-dns-ensure.sh" ]; then
    log INFO "Установка sa02m-dns-ensure.sh"
    install -m 755 "$ETC_DIR/../usr/local/sbin/sa02m-dns-ensure.sh" \
        /usr/local/sbin/sa02m-dns-ensure.sh
fi
if [ -f "$ETC_DIR/../usr/local/sbin/sa02m-wait-carrier.sh" ]; then
    log INFO "Установка sa02m-wait-carrier.sh"
    install -m 755 "$ETC_DIR/../usr/local/sbin/sa02m-wait-carrier.sh" \
        /usr/local/sbin/sa02m-wait-carrier.sh
fi
if [ -f "$ETC_DIR/systemd/system/sa02m-dns-ensure.service" ]; then
    log INFO "Установка sa02m-dns-ensure.service"
    install -m 644 "$ETC_DIR/systemd/system/sa02m-dns-ensure.service" \
        /etc/systemd/system/sa02m-dns-ensure.service
fi
# Drop-in'ы к ЧУЖИМ юнитам (ifup@, networking) — тот же идиом, что и
# docker.service.d/sa02m-kernel-guard.conf в 01-system.sh: install -d + install.
# Переустановка поверх существующего файла идемпотентна.
if [ -f "$ETC_DIR/systemd/system/ifup@.service.d/sa02m-carrier-wait.conf" ]; then
    log INFO "Установка drop-in ifup@.service.d/sa02m-carrier-wait.conf"
    install -d -m 755 "/etc/systemd/system/ifup@.service.d"
    install -m 644 "$ETC_DIR/systemd/system/ifup@.service.d/sa02m-carrier-wait.conf" \
        "/etc/systemd/system/ifup@.service.d/sa02m-carrier-wait.conf"
fi
if [ -f "$ETC_DIR/systemd/system/networking.service.d/sa02m-carrier-wait.conf" ]; then
    log INFO "Установка drop-in networking.service.d/sa02m-carrier-wait.conf"
    install -d -m 755 /etc/systemd/system/networking.service.d
    install -m 644 "$ETC_DIR/systemd/system/networking.service.d/sa02m-carrier-wait.conf" \
        /etc/systemd/system/networking.service.d/sa02m-carrier-wait.conf
fi

if [ -f "$ETC_DIR/fix-eth1-internet.sh" ]; then
    log INFO "Установка fix-eth1-internet.sh"
    install -m 755 "$ETC_DIR/fix-eth1-internet.sh" /usr/local/sbin/fix-eth1-internet.sh
fi

# Grat-ARP burst unit: content refresh only, deliberately NO enable —
# per-instance enablement (sa02m-grat-arp@ethN) stays whatever the device
# has; a fresh device is unaffected. daemon-reload runs below with the rest.
if [ -f "$ETC_DIR/systemd/system/sa02m-grat-arp@.service" ]; then
    log INFO "Установка sa02m-grat-arp@.service (обновление содержимого)"
    install -m 644 "$ETC_DIR/systemd/system/sa02m-grat-arp@.service" \
        /etc/systemd/system/sa02m-grat-arp@.service
fi

# Remove legacy phy-coldboot service if still present on this system
if [ -f /etc/systemd/system/sa02m-phy-coldboot.service ]; then
    systemctl stop sa02m-phy-coldboot 2>/dev/null || true
    systemctl disable sa02m-phy-coldboot 2>/dev/null || true
    rm -f /etc/systemd/system/sa02m-phy-coldboot.service
    log INFO "Удалён устаревший sa02m-phy-coldboot.service"
fi
rm -f /usr/local/bin/sa02m-phy-coldboot.sh

# ── Имена интерфейсов — канонические eth0/eth1 ────────────────────────────
# systemd `.link` файлы по-прежнему НЕ используются (откат 1.0.3.39 в силе):
# `.link` — это вход политики именования udev, и после обновления systemd/udev
# правило может потерять эффект → сеть слетает.
# Каноническое имя теперь обеспечивает sa02m-iface-canonical.service: он зовёт
# `ip link set ... name` (стабильный netlink ABI, от политики udev не зависит)
# перед networking.service и делает это КАЖДУЮ загрузку — то есть само чинится
# после apt upgrade, чего откату 1.0.3.39 как раз не хватало.
# Следствие: любой `.link` файл теперь — либо мусор, либо конкурирующий
# именователь, поэтому удаляем их безусловно, на любой плате.
# ПРАВИЛО БЕЗОПАСНОСТИ не изменилось: работающий интерфейс не переименовывается
# без явного opt-in (SA02M_CANONICAL_IFACE_NOW=1), см. блок в начале файла.
rm -f /etc/systemd/network/10-eth0.link /etc/systemd/network/10-eth1.link \
      /etc/systemd/network/11-eth0.link /etc/systemd/network/11-eth1.link \
      /etc/systemd/network/10-end0.link /etc/systemd/network/10-end1.link \
      /etc/systemd/network/11-end0.link /etc/systemd/network/11-end1.link 2>/dev/null || true
log INFO "Каноническое именование интерфейсов: sa02m-iface-canonical (.link файлы удалены)"

# ── nftables: kernel-aware ────────────────────────────────────────────────
# С 1.0.4.x kernel SA-02m (5.10.35) собран с CONFIG_NF_TABLES=y — nftables
# работает штатно. На старом kernel (5.10.35-sa02m+ без NF_TABLES) сервис
# фейлил с "Netlink socket: Protocol not supported" → маскировали. Проверяем
# и снимаем/накидываем маску в зависимости от возможностей ядра.
if grep -qE '^CONFIG_NF_TABLES=[ym]' "/boot/config-$(uname -r)" 2>/dev/null; then
    sa02m_svc_unmask nftables.service
    log INFO "nftables.service unmasked (kernel с CONFIG_NF_TABLES)"
else
    systemctl mask nftables.service >>"$LOG_FILE" 2>&1 || true
    log INFO "nftables.service masked (kernel без CONFIG_NF_TABLES)"
fi

systemctl daemon-reload >/dev/null 2>&1 || true
udevadm control --reload-rules 2>/dev/null || true

# Ключевой сервис для ifupdown: без него /etc/network/interfaces.d/*.conf
# не применяется при boot. На чистом Debian bullseye после debootstrap
# --variant=minbase preset не всегда включён — включаем явно.
sa02m_svc_apply networking.service infra start

# infra: enabled + unmasked in every mode (a stale /dev/null mask from
# imaging / old 01-system is repaired by the helper).
sa02m_svc_apply net-watchdog.service infra start
# Prefer unified eth0/eth1 coldboot; keep eth1 unit installed but disabled to
# avoid double ethtool -r on LAN1.
sa02m_svc_apply sa02m-eth-coldboot.service infra start
sa02m_systemctl disable sa02m-eth1-coldboot 2>/dev/null || true
sa02m_svc_apply sa02m-eth0-led-poll.service infra start
# ENABLE only, deliberately no `start`: the belt's job is the NEXT boot, and a
# live board must never be disturbed by an installer re-run. The unit only ever
# adds a resolver record when one is missing, so starting it would be harmless
# — the restraint is the installer's own rule, not a property of the helper.
sa02m_svc_apply sa02m-dns-ensure.service infra
# ENABLE only, deliberately no `start`: starting this unit performs the rename
# on a live board — exactly what the deferred-by-default rule above forbids
# without SA02M_CANONICAL_IFACE_NOW=1.
sa02m_svc_apply sa02m-iface-canonical.service infra
log OK "Network watchdog активирован"

# ── Миграция состояния на канонические имена (end0/end1 → eth0/eth1) ──────
# Idempotency floor (web-code-rigor.md): every step below is guarded on the
# legacy artefact still existing, so a second installer run is a pure no-op.
# Placed before "Apply now" so the LAN0_CONF_WRITTEN semantics there are
# unchanged. Full rationale: docs/contracts/ethernet-iface-naming.md.

# Copy a legacy interfaces.d conf onto its canonical name, substituting the
# interface name INSIDE the file (auto / iface / post-up lines all carry it).
# The stanza header is NORMALISED to $3 rather than carried over: in the
# DUAL-CONF window the legacy file has already been downgraded to
# `allow-hotplug`, so copying its header verbatim on a second installer run
# would silently demote the CANONICAL conf too — and `ifup -a` does not bring up
# an allow-hotplug stanza, i.e. the board would boot with no address.
canonical_conf_from_legacy() {
    local legacy=$1 canonical=$2 hdr=$3
    sed -e "s/^[[:space:]]*\(auto\|allow-hotplug\|allow-auto\)[[:space:]]\+${legacy}[[:space:]]*$/$hdr $canonical/" \
        -e "s/\b$legacy\b/$canonical/g" \
        "/etc/network/interfaces.d/$legacy.conf"
}

# migrate_iface_conf <legacy> <canonical> <canonical-header-kw> [protect]
# The header keyword mirrors what this installer writes itself: `auto` for LAN0
# (it must come up at boot) and `allow-hotplug` for LAN1.
migrate_iface_conf() {
    local legacy=$1 canonical=$2 hdr=$3 protect=${4:-0}
    local lconf="/etc/network/interfaces.d/$legacy.conf"
    local cconf="/etc/network/interfaces.d/$canonical.conf"
    local tmp
    [ -f "$lconf" ] || return 0

    # A legacy conf with no stanza carries nothing to migrate — it is either
    # hand-emptied or one the web panel retired to comments (it cannot delete a
    # file; see docs/contracts/ethernet-iface-naming.md §5.4). Copying it over
    # the canonical conf would wipe the real config, so just drop it — the
    # installer runs as root and a stanza-free file configures nothing.
    if ! grep -qE "^[[:space:]]*(auto|allow-[a-z]+|iface)[[:space:]]+$legacy([[:space:]]|\$)" "$lconf"; then
        rm -f "$lconf"
        log INFO "$legacy.conf без стансы — удалён (переносить нечего)"
        return 0
    fi

    # The gate. Migrating the conf on a board that then FAILS to rename is the
    # 1.0.3.38 "Cannot find device" disaster through a different door, so the
    # legacy conf is removed only when the rename is already a fact: the
    # canonical device is live, this is an image build, or the opt-in live
    # rename just succeeded.
    if [ -d "/sys/class/net/$canonical" ] || [ -n "${SA02M_ROOTFS_BUILD:-}" ] \
       || [ "$CANONICAL_RENAME_OK" = "1" ]; then
        if [ "$protect" = "1" ] && [ -f "$cconf" ]; then
            # This run wrote $cconf from an explicit --ip — that address is what
            # the operator asked for and the old one must not overwrite it.
            log INFO "$canonical.conf задан явно (--ip) — содержимое $legacy.conf не переносим"
        else
            canonical_conf_from_legacy "$legacy" "$canonical" "$hdr" > "$cconf"
        fi
        rm -f "$lconf"
        log OK "Миграция $legacy.conf → $canonical.conf"
        return 0
    fi

    # DUAL-CONF: the rename is deferred to the next boot, so write the canonical
    # conf now AND keep the legacy one at the same address as `allow-hotplug`.
    #   rename succeeds → `ifup -a` brings up `auto $canonical`; the legacy
    #     stanza is ignored (ifup -a does not touch allow-hotplug) and its device
    #     is gone, so networking.service stays clean — no failed unit.
    #   rename fails    → the legacy device is still there and udev's hotplug
    #     path brings it up on the same address, so the board stays reachable.
    # The next installer run sees the canonical device and drops the legacy
    # conf — the duplication window is exactly one boot.
    if [ "$protect" != "1" ] || [ ! -f "$cconf" ]; then
        canonical_conf_from_legacy "$legacy" "$canonical" "$hdr" > "$cconf"
    fi
    tmp=$(mktemp) || return 0
    if sed "s/^[[:space:]]*auto[[:space:]]\+${legacy}[[:space:]]*$/allow-hotplug $legacy/" \
        "$lconf" > "$tmp"; then
        cat "$tmp" > "$lconf"
    fi
    rm -f "$tmp"
    log WARN "$canonical.conf создан; $legacy.conf оставлен как allow-hotplug до перезагрузки"
}

MIGRATE_PROTECT0=0
if [ "${IP_EXPLICIT:-0}" = "1" ] && [ "$LAN0_CONF_WRITTEN" = "1" ]; then
    MIGRATE_PROTECT0=1
fi
migrate_iface_conf end0 eth0 auto "$MIGRATE_PROTECT0"
migrate_iface_conf end1 eth1 allow-hotplug

# WATCHDOG_PING_<IFACE>: fix-eth.sh derives the variable name from the LIVE
# interface name uppercased, so a documented WATCHDOG_PING_END0 silently stops
# being read once the interface is eth0. Add the ETH* counterpart with the same
# value; the operator's legacy line is never deleted.
migrate_watchdog_ping() {
    local lname=$1 cname=$2 f=/etc/sa02m_network.conf val
    [ -f "$f" ] || return 0
    grep -qE "^[[:space:]]*WATCHDOG_PING_${cname}=" "$f" && return 0
    val=$(sed -n "s/^[[:space:]]*WATCHDOG_PING_${lname}=[[:space:]]*\(.*\)$/\1/p" "$f" | head -1)
    [ -n "$val" ] || return 0
    printf '\n# Добавлено установщиком при переходе на канонические имена (%s → %s);\n# старая строка оставлена без изменений.\nWATCHDOG_PING_%s=%s\n' \
        "$lname" "$cname" "$cname" "$val" >> "$f"
    log OK "sa02m_network.conf: добавлен WATCHDOG_PING_${cname}"
}
migrate_watchdog_ping END0 ETH0
migrate_watchdog_ping END1 ETH1

# The dhclient default-route hook is generated with the interface name
# interpolated, so it goes stale when that interface is renamed. Regenerate it
# only when it still names a legacy interface, and only when the content really
# changes — a re-run rewrites nothing.
DHCP_HOOK_F=/etc/dhcp/dhclient-exit-hooks.d/eth1-default-route
if [ -f "$DHCP_HOOK_F" ] && grep -qE '(^|[^a-z0-9])end[01]([^a-z0-9]|$)' "$DHCP_HOOK_F"; then
    DHCP_HOOK_TMP=$(mktemp) || DHCP_HOOK_TMP=""
    if [ -n "$DHCP_HOOK_TMP" ]; then
        sed 's/\bend0\b/eth0/g; s/\bend1\b/eth1/g' "$DHCP_HOOK_F" > "$DHCP_HOOK_TMP"
        if ! cmp -s "$DHCP_HOOK_TMP" "$DHCP_HOOK_F"; then
            cat "$DHCP_HOOK_TMP" > "$DHCP_HOOK_F"
            chmod 755 "$DHCP_HOOK_F"
            log OK "dhclient exit hook переведён на канонические имена"
        fi
        rm -f "$DHCP_HOOK_TMP"
    fi
fi

if [ -z "${SA02M_ROOTFS_BUILD:-}" ] \
   && { [ -d /sys/class/net/end0 ] || [ -d /sys/class/net/end1 ]; }; then
    log WARN "Обнаружены legacy-имена (end0/end1) — требуется перезагрузка для применения канонических имён eth0/eth1"
fi

# ── Ремонт gateway / dns-nameservers в СУЩЕСТВУЮЩЕМ конфиге ───────────────
# Блок выше намеренно НЕ перезаписывает уже существующий $LAN0.conf (это сбросило
# бы статический IP, заданный оператором). Следствие: если сторонний писатель
# (наблюдалось: внешний инструмент привязки MAC) вырезал из стансы `gateway` и
# `dns-nameservers`, чинить это некому — плата остаётся без маршрута и DNS, и ни
# один запуск установщика этого не исправляет.
#
# Правила ремонта и их обоснование (только добавляем отсутствующее; проверка
# подсети обязательна; всё остальное fail-closed) — единственный дом:
# docs/contracts/ethernet-iface-naming.md §3.1. Здесь не пересказываем.
#
# Локальное «почему именно тут»: ставится ПОСЛЕ migrate_iface_conf (работаем по
# каноническому конфигу, а не по legacy) и ДО «Apply now» (ремонт не должен
# зависеть от того, тронул ли этот запуск живой интерфейс).
# Тест: scripts/dev/test-iface-gw-repair.sh (строка реестра iface-gw-repair).

# ensure_gw_dns <iface> <gateway> <dns-servers>
# Устанавливает GW_REPAIR_ADDED_GW=1, если строка gateway была реально добавлена
# (вызывающий по этому решает, нужно ли поднимать маршрут вживую).
ensure_gw_dns() {
    local iface=$1 gw=$2 dns=$3
    local conf="/etc/network/interfaces.d/$iface.conf"
    local i n start end anchor indent addr mask cidr_mask tmp line
    local n_addr n_mask exp_lines got_lines verify_missing
    local nstart nend ngw ndns
    local have_gw=0 have_dns=0 write_gw=0 write_dns=0
    local -a lines=() nlines=()
    GW_REPAIR_ADDED_GW=0

    if [ "${SA02M_SKIP_GW_REPAIR:-0}" = "1" ]; then
        log INFO "SA02M_SKIP_GW_REPAIR=1 — ремонт gateway/dns для $iface пропущен"
        return 0
    fi
    # Имя интерфейса уходит в регулярное выражение — берём только безопасную форму.
    case "$iface" in
        ''|*[!a-zA-Z0-9._-]*) log WARN "ремонт gateway/dns: недопустимое имя интерфейса '$iface'"; return 0 ;;
    esac
    # Файла нет — создание это работа блока записи выше, не ремонта.
    [ -f "$conf" ] || return 0

    # Ровно одна станса: в файл, который мы не смогли однозначно разобрать, не
    # вмешиваемся (то же правило, что и у панели при дубле стансы).
    n=$(grep -cE "^[[:space:]]*iface[[:space:]]+${iface}[[:space:]]+inet[[:space:]]" "$conf")
    if [ "$n" != "1" ]; then
        log WARN "$conf: найдено стансов 'iface $iface inet' — $n (ожидалась 1); ремонт gateway/dns пропущен"
        return 0
    fi
    if ! grep -qE "^[[:space:]]*iface[[:space:]]+${iface}[[:space:]]+inet[[:space:]]+static([[:space:]]|\$)" "$conf"; then
        log INFO "$conf: станса не 'inet static' — ремонт gateway/dns не применяется (маршрут DHCP владеет сам)"
        return 0
    fi

    while IFS= read -r line || [ -n "$line" ]; do lines+=("$line"); done < "$conf"

    start=-1
    for ((i = 0; i < ${#lines[@]}; i++)); do
        if [[ ${lines[i]} =~ ^[[:space:]]*iface[[:space:]]+${iface}[[:space:]]+inet[[:space:]] ]]; then
            start=$i
            break
        fi
    done
    [ "$start" -ge 0 ] || return 0

    # Тело стансы — до следующей строки верхнего уровня (или до конца файла).
    end=${#lines[@]}
    for ((i = start + 1; i < ${#lines[@]}; i++)); do
        if [[ ${lines[i]} =~ ^[[:space:]]*(auto|allow-[a-z]+|iface|source|mapping)([[:space:]]|$) ]]; then
            end=$i
            break
        fi
    done

    # Разбор тела. Закомментированный ключ СЧИТАЕТСЯ присутствующим: `#gateway …`
    # — осознанное действие человека (такая форма есть и в вендорских конфигах),
    # а правило ремонта — добавлять только ОТСУТСТВУЮЩЕЕ. Ошибаемся в сторону
    # «никогда не спорить с оператором».
    anchor=-1
    # Отступ по умолчанию — четыре пробела; ниже его перебивает отступ реальной
    # строки address (конфиги на платах разные: где-то четыре пробела, где-то
    # нулевой отступ, где-то TAB).
    indent="    "
    addr=""
    mask=""
    cidr_mask=""
    n_addr=0
    n_mask=0
    for ((i = start + 1; i < end; i++)); do
        if [[ ${lines[i]} =~ ^[[:space:]]*#?[[:space:]]*gateway[[:space:]] ]]; then
            have_gw=1
        fi
        if [[ ${lines[i]} =~ ^[[:space:]]*#?[[:space:]]*dns-nameservers[[:space:]] ]]; then
            have_dns=1
        fi
        if [[ ${lines[i]} =~ ^([[:space:]]*)address[[:space:]]+([^[:space:]]+) ]]; then
            indent=${BASH_REMATCH[1]}
            addr=${BASH_REMATCH[2]}
            n_addr=$((n_addr + 1))
        fi
        if [[ ${lines[i]} =~ ^[[:space:]]*netmask[[:space:]]+([^[:space:]]+) ]]; then
            mask=${BASH_REMATCH[1]}
            n_mask=$((n_mask + 1))
        fi
        # Точка вставки — после ПОСЛЕДНЕЙ адресной строки тела; всё остальное
        # (hwaddress, post-up, комментарии, metric) остаётся на своих местах.
        if [[ ${lines[i]} =~ ^[[:space:]]*(address|netmask|broadcast|network)([[:space:]]|$) ]]; then
            anchor=$i
        fi
    done
    [ "$anchor" -ge 0 ] || anchor=$start

    # Оба ключа на месте — выходим, не трогая даже mtime и не ругаясь на форму
    # файла, которую нам всё равно не нужно понимать.
    if [ "$have_gw" = "1" ] && [ "$have_dns" = "1" ]; then
        return 0
    fi

    # ── Разбор адреса и маски; всё, что не разобралось — fail closed ────────
    # «Не разобралось» ⇒ не пишем НИЧЕГО (ни gateway, ни dns): файл, который мы
    # не понимаем, не наш, чтобы его править — то же правило, что и для дубля
    # стансы выше. Каждая ветка обязана сказать в логе, что именно она увидела:
    # журнал установки — единственная поверхность отказа у этого кода.
    if ! declare -F same_ipv4_subnet >/dev/null 2>&1 \
       || ! declare -F netmask_is_contiguous >/dev/null 2>&1 \
       || ! declare -F sa02m_prefix_to_netmask >/dev/null 2>&1; then
        log WARN "$conf: математика подсетей недоступна — ремонт gateway/dns пропущен (fail closed)"
        return 0
    fi
    # Дубль ключа внутри одной стансы: ifupdown такой конфиг сам считает
    # ошибочным, а для нас он опасен конкретно — две строки netmask позволяли
    # проверке подсети «выбрать» ту, что пропустит чужой шлюз. Единственная
    # найденная дыра в гарантии; закрываем тем же fail-closed.
    if [ "$n_addr" -gt 1 ] || [ "$n_mask" -gt 1 ]; then
        log WARN "$conf: в стансе повторяется ключ (address×$n_addr, netmask×$n_mask) — ремонт gateway/dns пропущен (fail closed)"
        return 0
    fi
    if [ "$n_addr" = "0" ]; then
        log WARN "$conf: в стансе нет строки address — ремонт gateway/dns пропущен (fail closed)"
        return 0
    fi
    # Современная форма `address 192.168.1.136/24` — валидная станса ifupdown
    # вообще без строки netmask. Разбираем префикс, иначе исправный конфиг
    # молча не чинился бы.
    if [[ "$addr" =~ ^([^/]+)/([^/]+)$ ]]; then
        if ! cidr_mask=$(sa02m_prefix_to_netmask "${BASH_REMATCH[2]}"); then
            log WARN "$conf: префикс '/${BASH_REMATCH[2]}' в строке address не разбирается — ремонт gateway/dns пропущен (fail closed)"
            return 0
        fi
        addr=${BASH_REMATCH[1]}
        if [ "$n_mask" = "1" ] && [ "$mask" != "$cidr_mask" ]; then
            log WARN "$conf: префикс address (=$cidr_mask) и строка netmask ($mask) противоречат друг другу — ремонт gateway/dns пропущен (fail closed)"
            return 0
        fi
        mask=$cidr_mask
    fi
    if [ -z "$mask" ]; then
        log WARN "$conf: у address $addr нет маски (ни строки netmask, ни /префикса) — ремонт gateway/dns пропущен (fail closed)"
        return 0
    fi
    if ! ipv4_to_int "$addr" >/dev/null || ! netmask_is_contiguous "$mask"; then
        log WARN "$conf: address '$addr' / маска '$mask' не разбираются — ремонт gateway/dns пропущен (fail closed)"
        return 0
    fi

    # Станса прочитана, но КАНДИДАТ в шлюзы оказался вне её подсети: gateway не
    # пишем, а вот dns-nameservers добавить безопасно — строка DNS не может
    # сделать плату недоступной.
    if [ "$have_gw" = "0" ]; then
        if [ -z "$gw" ]; then
            log WARN "$conf: gateway отсутствует, но кандидат не задан — не пишем"
        elif ! same_ipv4_subnet "$addr" "$gw" "$mask"; then
            log WARN "$conf: шлюз $gw вне подсети $addr/$mask — gateway НЕ добавлен (иначе ifup упадёт и плата станет недоступна)"
        else
            write_gw=1
        fi
    fi
    if [ "$have_dns" = "0" ] && [ -n "$dns" ]; then
        write_dns=1
    fi

    if [ "$write_gw" = "0" ] && [ "$write_dns" = "0" ]; then
        return 0
    fi

    # ── Запись. Каждый шаг проверяется, и ни один не «почти получился» ──────
    # Временный файл создаётся В ТОМ ЖЕ каталоге: замена делается через mv, а mv
    # через границу файловых систем — это copy+unlink, то есть снова неатомарно.
    # Имя `<conf>.sa02m-gwtmp.*` инертно по тому же фильтру `.conf`, что и бэкапы.
    tmp=$(mktemp "$conf.sa02m-gwtmp.XXXXXX") || {
        log WARN "$conf: не удалось создать временный файл — конфиг НЕ изменён"
        return 0
    }
    {
        for ((i = 0; i < ${#lines[@]}; i++)); do
            printf '%s\n' "${lines[i]}"
            if [ "$i" = "$anchor" ]; then
                if [ "$write_gw" = "1" ]; then
                    printf '%s%s\n' "$indent" "gateway $gw"
                fi
                if [ "$write_dns" = "1" ]; then
                    printf '%s%s\n' "$indent" "dns-nameservers $dns"
                fi
            fi
        done
    } > "$tmp"

    # Сборка удалась целиком? Оборванная запись (ENOSPC — на плате, где поводом
    # для этой правки как раз был переполненный /var/log, это не гипотеза) даёт
    # короткий файл. Считаем строки, а не верим коду возврата redirect'а.
    exp_lines=$(( ${#lines[@]} + write_gw + write_dns ))
    got_lines=$(wc -l < "$tmp" 2>/dev/null | tr -d '[:space:]')
    if [ "$got_lines" != "$exp_lines" ]; then
        log WARN "$conf: временный файл собран не полностью ($got_lines строк вместо $exp_lines) — конфиг НЕ изменён"
        rm -f "$tmp"
        return 0
    fi

    # Второй предохранитель идемпотентности. Основной — ранний выход выше (нечего
    # добавлять ⇒ файла не касаемся вовсе); эта проверка ловит случай «решили
    # писать, а вышло байт в байт то же». Поведения она сегодня не меняет —
    # оставлена как страховка на будущие ветки записи (см. заметку в
    # scripts/dev/test-iface-gw-repair.sh).
    if cmp -s "$tmp" "$conf"; then
        rm -f "$tmp"
        return 0
    fi

    # Суффикс .sa02m-gwbak, а НЕ .sa02m-bak: последнее — точка восстановления
    # панели (контракт §5.4), запуск установщика не вправе её затирать.
    # Не удалось снять копию — не пишем вовсе: замена без точки отката это
    # ровно тот риск, ради которого копия и делается.
    if ! cp -f "$conf" "$conf.sa02m-gwbak"; then
        log WARN "$conf: не удалось снять резервную копию .sa02m-gwbak — конфиг НЕ изменён"
        rm -f "$tmp"
        return 0
    fi

    # Права и владельца берём с оригинала: mktemp создаёт файл 600, а конфиг
    # интерфейса на плате — 644 root:root.
    chmod --reference="$conf" "$tmp" 2>/dev/null || chmod 644 "$tmp" 2>/dev/null || true
    chown --reference="$conf" "$tmp" 2>/dev/null || true

    # Атомарная замена: rename(2) в пределах каталога — либо старый файл целиком,
    # либо новый целиком. Прежний `cat > "$conf"` сохранял inode, но при обрыве
    # записи оставлял ОБРЕЗАННЫЙ eth0.conf — плата без адреса, ровно тот исход,
    # от которого защищает весь остальной дизайн. Inode при mv меняется; это
    # безопасно: fd на конфиг интерфейса никто не держит, ifup читает его заново.
    if ! mv -f "$tmp" "$conf"; then
        log WARN "$conf: не удалось заменить конфиг (mv) — файл остался прежним"
        rm -f "$tmp"
        return 0
    fi

    # Пост-условие проверяем ЧТЕНИЕМ файла, а не доверием к записи. Дальше по
    # флагу GW_REPAIR_ADDED_GW поднимается живой маршрут и пишется resolvconf
    # head; ложное «OK» создало бы head со шлюзом, которого в конфиге нет — ту
    # самую патологию, которую снимает sa02m_write_resolvconf_head.
    # Считаем В ТЕХ ЖЕ границах стансы, в которых принималось решение: строка с
    # тем же текстом в СОСЕДНЕЙ стансе не должна ни подтверждать нашу запись, ни
    # (что хуже) откатывать верную.
    verify_missing=""
    nstart=-1
    ngw=0
    ndns=0
    while IFS= read -r line || [ -n "$line" ]; do nlines+=("$line"); done < "$conf"
    for ((i = 0; i < ${#nlines[@]}; i++)); do
        if [[ ${nlines[i]} =~ ^[[:space:]]*iface[[:space:]]+${iface}[[:space:]]+inet[[:space:]] ]]; then
            nstart=$i
            break
        fi
    done
    if [ "$nstart" -ge 0 ]; then
        nend=${#nlines[@]}
        for ((i = nstart + 1; i < ${#nlines[@]}; i++)); do
            if [[ ${nlines[i]} =~ ^[[:space:]]*(auto|allow-[a-z]+|iface|source|mapping)([[:space:]]|$) ]]; then
                nend=$i
                break
            fi
        done
        for ((i = nstart + 1; i < nend; i++)); do
            if [ "${nlines[i]}" = "${indent}gateway $gw" ]; then
                ngw=$((ngw + 1))
            fi
            if [ "${nlines[i]}" = "${indent}dns-nameservers $dns" ]; then
                ndns=$((ndns + 1))
            fi
        done
    fi
    if [ "$write_gw" = "1" ] && [ "$ngw" != "1" ]; then
        verify_missing="gateway"
    fi
    if [ "$write_dns" = "1" ] && [ "$ndns" != "1" ]; then
        verify_missing="${verify_missing:+$verify_missing, }dns-nameservers"
    fi
    if [ -n "$verify_missing" ]; then
        # Откат тоже проверяем: не проверив его, мы бы написали в лог «конфиг
        # восстановлен» о файле, который восстановить не удалось, — та же ложь в
        # логе, только на один отказ глубже.
        if cp -f "$conf.sa02m-gwbak" "$conf"; then
            log WARN "$conf: после записи не подтвердились строки ($verify_missing) — конфиг восстановлен из $conf.sa02m-gwbak"
        else
            log ERR "$conf: после записи не подтвердились строки ($verify_missing), И ОТКАТ НЕ УДАЛСЯ — состояние конфига НЕОПРЕДЕЛЁННОЕ. Проверьте вручную: $conf и резервная копия $conf.sa02m-gwbak"
        fi
        return 0
    fi

    if [ "$write_gw" = "1" ] && [ "$write_dns" = "1" ]; then
        log OK "$conf: добавлены gateway $gw и dns-nameservers $dns"
    elif [ "$write_gw" = "1" ]; then
        log OK "$conf: добавлен gateway $gw"
    else
        log OK "$conf: добавлены dns-nameservers $dns"
    fi
    GW_REPAIR_ADDED_GW=$write_gw
    return 0
}
# ── end ensure_gw_dns (маркер конца извлечения для test-iface-gw-repair.sh) ──

GW_REPAIR_ADDED_GW=0
ensure_gw_dns "$LAN0" "$GATEWAY" "$DNS_SERVERS"   # LAN1 не передаём: маршрутом владеет DHCP

# Живое применение — только НЕНАРУШАЮЩЕЕ. `ip route replace` не трогает адрес,
# поэтому SSH-сессия установщика переживает его; `ifup`/`ifdown` здесь запрещены
# (перезапуск интерфейса рвёт управляющий линк посреди установки — ровно то, от
# чего защищает LAN0_CONF_WRITTEN в блоке «Apply now» ниже).
# Зачем вообще чинить вживую: install.sh запускает 01-system.sh ДО этого файла,
# так что правки только в конфиге оставили бы текущий запуск без DNS, и
# 07-nodered.sh дальше опять не достучится до registry.npmjs.org.
if [ "$GW_REPAIR_ADDED_GW" = "1" ] && [ -z "${SA02M_ROOTFS_BUILD:-}" ] \
   && [ -z "$(ip route show default 2>/dev/null)" ]; then
    if ip route replace default via "$GATEWAY" dev "$LAN0" >> "$LOG_FILE" 2>&1; then
        log OK "Маршрут по умолчанию восстановлен: default via $GATEWAY dev $LAN0"
        sa02m_write_resolvconf_head "$GATEWAY"
        resolvconf -u 2>/dev/null || true
    else
        log WARN "ip route replace default via $GATEWAY dev $LAN0 не удался — маршрут появится после перезагрузки (ifup применит новую строку)"
    fi
fi

# ── Apply now ─────────────────────────────────────────────────────────────
# Flush + ifup ONLY when this run actually (re)wrote $LAN0.conf. On a plain
# re-run that preserved an existing config the interface is already up with the
# operator's IP — flushing it would drop the live management link (SSH). Skip in
# rootfs build (no live interface to apply).
if [ -z "${SA02M_ROOTFS_BUILD:-}" ] && [ "$LAN0_CONF_WRITTEN" = "1" ]; then
    log INFO "Поднимаем $NET_IFACE"
    ip link set "$NET_IFACE" up 2>/dev/null || true
    ip addr flush dev "$NET_IFACE" 2>/dev/null || true
    ifup "$NET_IFACE" >> "$LOG_FILE" 2>&1 || true
elif [ -z "${SA02M_ROOTFS_BUILD:-}" ]; then
    log INFO "$NET_IFACE: конфиг сохранён без изменений — не трогаем живой интерфейс"
fi

log OK "=== [02] Сеть настроена: $IP_ADDRESS ==="
