#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# СА-02м  •  Shared functions for install scripts
# ═══════════════════════════════════════════════════════════════════════════

LOG_FILE="${LOG_FILE:-/var/log/sa02m_install.log}"

log() {
    local level=${1:-INFO} msg=$2
    local ts; ts=$(date '+%Y-%m-%d %H:%M:%S')
    local color reset
    case "$level" in
        OK)   color='\033[0;32m' ;;
        WARN) color='\033[0;33m' ;;
        ERR)  color='\033[0;31m' ;;
        *)    color='\033[0;36m' ;;
    esac
    reset='\033[0m'
    echo -e "${color}[${ts}] [${level}] ${msg}${reset}"
    echo    "[${ts}] [${level}] ${msg}" >> "$LOG_FILE" 2>/dev/null || true
}

sa02m_board_model() {
    tr -d '\0' < /proc/device-tree/model 2>/dev/null \
        || awk -F: '/^Hardware/{gsub(/^[ \t]+/,"",$2);print $2;exit}' /proc/cpuinfo 2>/dev/null \
        || true
}

sa02m_serial_profile_from_file() {
    local conf=${1:-/etc/sa02m_serial_profile.conf}
    local value
    [ -f "$conf" ] || return 1
    value=$(awk -F= '/^SA02M_SERIAL_PROFILE=/{gsub(/^[ \t"]+|[ \t"]+$/,"",$2); print $2; exit}' "$conf" 2>/dev/null)
    case "$value" in
        sa02m-1eth|sa02m-2eth)
            printf '%s\n' "$value"
            return 0
            ;;
    esac
    return 1
}

sa02m_serial_profile() {
    case "${SA02M_SERIAL_PROFILE:-}" in
        sa02m-1eth|sa02m-2eth)
            printf '%s\n' "${SA02M_SERIAL_PROFILE}"
            return 0
            ;;
    esac

    if sa02m_serial_profile_from_file "/etc/sa02m_serial_profile.conf"; then
        return 0
    fi

    if [ -d /sys/class/net/eth1 ]; then
        printf '%s\n' "sa02m-2eth"
    else
        printf '%s\n' "sa02m-1eth"
    fi
}

sa02m_serial_targets() {
    local profile=${1:-$(sa02m_serial_profile)}
    case "$profile" in
        sa02m-2eth)
            printf '%s\n' "ttyS3 ttyS4 ttyS5 ttyS7"
            ;;
        *)
            printf '%s\n' "ttyS0 ttyS3 ttyS4 ttyS5 ttyS7"
            ;;
    esac
}

write_sa02m_serial_map_conf() {
    local dst=${1:-/etc/sa02m_serial_map.conf}
    local profile model tmp idx com_idx
    local -a targets

    profile=$(sa02m_serial_profile)
    model=$(sa02m_board_model)
    read -r -a targets <<< "$(sa02m_serial_targets "$profile")"
    tmp="${dst}.tmp.$$"

    {
        echo "# Generated by SA-02m installer"
        echo "SA02M_BOARD_MODEL=\"${model}\""
        echo "SA02M_SERIAL_PROFILE=${profile}"
        echo "SA02M_SERIAL_COUNT=${#targets[@]}"
        idx=0
        for tty in "${targets[@]}"; do
            com_idx=$(( idx + 1 ))
            echo "SA02M_TTY_${idx}=${tty}"
            echo "SA02M_RS485_${idx}=RS-485-${idx}"
            echo "SA02M_COM_${com_idx}=COM${com_idx}"
            idx=$(( idx + 1 ))
        done
    } > "$tmp"

    install -m 644 "$tmp" "$dst"
    rm -f "$tmp"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        log ERR "Запустите скрипт от root: sudo $0"
        exit 1
    fi
}

# systemctl с таймаутом — защита от зависания при сбое D-Bus (Armbian, нагрузка MPLC и т.д.).
SA02M_SYSTEMCTL_TIMEOUT_SEC="${SA02M_SYSTEMCTL_TIMEOUT_SEC:-35}"

sa02m_systemctl() {
    local sec=${SA02M_SYSTEMCTL_TIMEOUT_SEC:-35}
    if command -v timeout >/dev/null 2>&1; then
        timeout "$sec" systemctl "$@"
    else
        systemctl "$@"
    fi
}

pkg_install() {
    local pkgs=("$@")
    local missing=()
    for p in "${pkgs[@]}"; do
        dpkg -l "$p" &>/dev/null || missing+=("$p")
    done
    if [ ${#missing[@]} -gt 0 ]; then
        log INFO "Установка пакетов: ${missing[*]}"
        apt-get install -y "${missing[@]}" >> "$LOG_FILE" 2>&1
    fi
}

svc_enable() {
    sa02m_systemctl enable "$1" >> "$LOG_FILE" 2>&1 || true
    sa02m_systemctl start  "$1" >> "$LOG_FILE" 2>&1 || true
}

svc_restart() {
    sa02m_systemctl restart "$1" >> "$LOG_FILE" 2>&1 || true
}
