#!/bin/bash
# SA-02m: apply hardware variant — recreates serial symlinks and udev rules.
# Self-contained: embeds required functions from lib.sh.
# Must run as root. Called by variant.cgi via sudo.
# Usage: sa02m-apply-variant.sh <sa02m-1eth|sa02m-2eth>

set -euo pipefail

sa02m_serial_targets() {
    local profile=${1:-sa02m-1eth}
    case "$profile" in
        sa02m-2eth)
            printf '%s\n' "ttyS3 ttyS4 ttyS5 ttyS7"
            ;;
        *)
            printf '%s\n' "ttyS0 ttyS3 ttyS4 ttyS5 ttyS7"
            ;;
    esac
}

sa02m_board_model() {
    tr -d '\0' < /proc/device-tree/model 2>/dev/null \
        || awk -F: '/^Hardware/{gsub(/^[ \t]+/,"",$2);print $2;exit}' /proc/cpuinfo 2>/dev/null \
        || true
}

write_sa02m_serial_map_conf() {
    local dst=${1:-/etc/sa02m_serial_map.conf}
    local profile=$2
    local model
    local -a targets
    local tmp idx com_idx

    model=$(sa02m_board_model)
    read -r -a targets <<< "$(sa02m_serial_targets "$profile")"
    tmp="${dst}.tmp.$$"

    {
        echo "# Generated by SA-02m variant selector"
        echo "SA02M_BOARD_MODEL=\"${model}\""
        echo "SA02M_SERIAL_PROFILE=${profile}"
        echo "SA02M_SERIAL_COUNT=${#targets[@]}"
        idx=0
        for tty in "${targets[@]}"; do
            com_idx=$(( idx + 1 ))
            echo "SA02M_TTY_${idx}=${tty}"
            echo "SA02M_RS485_${idx}=RS-485-${idx}"
            echo "SA02M_COM_${com_idx}=COM${com_idx}"
            idx=$(( idx + 1 ))
        done
    } > "$tmp"

    install -m 644 "$tmp" "$dst"
    rm -f "$tmp"
}

# ── Main ────────────────────────────────────────────────────────────────────

VARIANT="${1:-}"
case "$VARIANT" in
    sa02m-1eth|sa02m-2eth) ;;
    *)
        printf '{"ok":false,"error":"invalid_variant"}\n'
        exit 1
        ;;
esac

# Persist variant
printf 'SA02M_HW_VARIANT=%s\n' "$VARIANT" > /etc/sa02m_hw_variant.conf
chmod 644 /etc/sa02m_hw_variant.conf

read -r -a SERIAL_TARGETS <<< "$(sa02m_serial_targets "$VARIANT")"

# Remove stale symlinks (up to 5 ports)
for stale_idx in 0 1 2 3 4; do
    rm -f "/dev/RS-485-${stale_idx}" "/dev/COM$(( stale_idx + 1 ))"
done

# Create symlinks
for idx in "${!SERIAL_TARGETS[@]}"; do
    tty="${SERIAL_TARGETS[$idx]}"
    com_idx=$(( idx + 1 ))
    target="/dev/${tty}"
    [ -e "$target" ] && ln -sf "$target" "/dev/RS-485-${idx}" || true
    [ -e "$target" ] && ln -sf "$target" "/dev/COM${com_idx}"   || true
done

# Write udev rules
UDEV_RULE="/etc/udev/rules.d/99-sa02m-serial.rules"
{
    printf '# Generated by SA-02m variant selector\n'
    for idx in "${!SERIAL_TARGETS[@]}"; do
        tty="${SERIAL_TARGETS[$idx]}"
        com_idx=$(( idx + 1 ))
        printf 'KERNEL=="%s", SYMLINK+="RS-485-%d COM%d"\n' "$tty" "$idx" "$com_idx"
    done
} > "$UDEV_RULE"
udevadm control --reload-rules 2>/dev/null || true

# Update serial map config
write_sa02m_serial_map_conf /etc/sa02m_serial_map.conf "$VARIANT"

# Re-map link LEDs (eth0_link/eth1_link) for the new variant
if [ -x /usr/local/bin/sa02m-eth0-led.sh ]; then
    /usr/local/bin/sa02m-eth0-led.sh || true
fi
systemctl try-restart sa02m-eth0-led-poll.service 2>/dev/null || true

SERIAL_COUNT=${#SERIAL_TARGETS[@]}
printf '{"ok":true,"variant":"%s","serial_count":%d}\n' "$VARIANT" "$SERIAL_COUNT"
