d /etc/sa02m-agent-api 0750 root www-data -
d /etc/sa02m-agent-api/root-cap 0700 root root -
f /etc/sa02m-agent-api/tokens.json 0640 root www-data -
d /var/log/sa02m-agent-api 0750 www-data adm -
d /opt/sa02m-user 2775 sa02m-user www-data -
